import React from "react";

export default class RenderLoader extends React.Component
{
	constructor(props)
	{
		super(props);

		this.state=
		{
			base64EncodedLoaderHTML: "PHN0eWxlPgoJLmNpcmNsZQoJewoJCXBvc2l0aW9uOiBhYnNvbHV0ZTsKCgkJbGVmdDogNTB2dzsKCQl0b3A6IDUwdmg7CgoJCWJvcmRlci1yYWRpdXM6IDUwJTsKCgkJYmFja2dyb3VuZC1jb2xvcjogIzdmYjkwMDsKCX0KCgkuc3RhdGljCgl7CgkJd2lkdGg6IDIwcHg7CgkJaGVpZ2h0OiAyMHB4OwoKCQl0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTUwJSkgdHJhbnNsYXRlWSgtNTAlKTsKCX0KCgkuZXhwYW5kaW5nCgl7CgkJd2lkdGg6IDE1NXB4OwoJCWhlaWdodDogMTU1cHg7CgoJCW9wYWNpdHk6IDAuMDsKCgkJYW5pbWF0aW9uOiAycyBpbmZpbml0ZSBlYXNlLW91dCBleHBhbmRpbmdDaXJjbGVBbmltYXRpb247CgoJCXRyYW5zZm9ybTogdHJhbnNsYXRlWCgtNTAlKSB0cmFuc2xhdGVZKC01MCUpIHNjYWxlKDAuNSk7Cgl9CgoJQGtleWZyYW1lcyBleHBhbmRpbmdDaXJjbGVBbmltYXRpb24KCXsKCQkwJQoJCXsKCQkJdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpIHRyYW5zbGF0ZVkoLTUwJSkgc2NhbGUoMC41KTsKCgkJCW9wYWNpdHk6IDAuMDsKCQl9CgoJCTI1JQoJCXsKCQkJdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpIHRyYW5zbGF0ZVkoLTUwJSkgc2NhbGUoMC43NSk7CgoJCQlvcGFjaXR5OiAwLjI7CgkJfQoKCQkxMDAlCgkJewoJCQl0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTUwJSkgdHJhbnNsYXRlWSgtNTAlKSBzY2FsZSgxLjApOwoKCQkJb3BhY2l0eTogMC4wOwoJCX0KCX0KPC9zdHlsZT4KCjxkaXYgaWQ9J2xvYWRlcic+Cgk8ZGl2IGNsYXNzPSdjaXJjbGUgZXhwYW5kaW5nJz48L2Rpdj4KCTxkaXYgY2xhc3M9J2NpcmNsZSBleHBhbmRpbmcnIHN0eWxlPSdhbmltYXRpb24tZGVsYXk6IDAuNzVzJz48L2Rpdj4KCTxkaXYgY2xhc3M9J2NpcmNsZSBzdGF0aWMnPjwvZGl2Pgo8L2Rpdj4K"
		}; //base64EncodedLoaderHTML contains the Base64 encoded HTML code of the loader
	}

	render()
	{
		return <div dangerouslySetInnerHTML={{__html: atob(this.state.base64EncodedLoaderHTML)}}/>;
	}
}
